apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject2
  template:
    metadata:
      labels:
        app: myproject2
    spec:
      containers:
      - name: myproject2
        image: myproject2:1.0
        ports:
        - containerPort: 8082 


---

apiVersion: v1
kind: Service
metadata:
  name: myproject2-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8082
      targetPort: 8082 
      nodePort: 30001
  
         
