kind: Deployment
apiVersion: apps/v1
metadata:
  name: myproject2-deployment
spec:
  replicas: 3
  minReadySeconds: 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        
  selector:
    matchLabels:
      app: myproject2
  template:
    metadata:
      name: myproject2
      labels:
        app: myproject2
    spec:
      containers:
       - name: healthcare
         image: pavan1432/myproject2:1.0
         ports:
         - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: myproject2-service
spec:
  selector:
    app: myproject2 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
         
